### PR TITLE
Fix for #309

### PR DESCRIPTION
**Pull request by rhaxton**
Changed sr_document.dcm test case to have a LongCodeValue tag for Language of Content

Changed search_tree in find_content_items to try all three CodeValue tags (CodeValue, LongCodeValue, URNCodeValue)

### CODE REVIEW

**Comment by CPBridge** [comment]
Hi @rhaxton, thanks for the PR. I think your code changes are good, except for the failing style checks: https://github.com/ImagingDataCommons/highdicom/actions/runs/11187492783/job/31122527504?pr=310

However, I have one nitpick... I notice that you have changed the attribute used for language code in the example SR document to Long Code Value but do not change the value (`121049`). However, to be 100% strict about this, that is an invalid usage because the standard states ([part 3 chapter 8 section 8.1](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/chapter_8.html#sect_8.1)):

> The Long Code Value (0008,0119) or URN Code Value (0008,0120) is only used for codes that exceed the 16 character size limit of Code Value (0008,0100). If the code value length exceeds 16, the Code Value (0008,0100) shall not be present. If the code value length is 16 characters or less, the Code Value (0008,0100) shall contain the code and neither Long Code Value (0008,0119) nor URN Code Value (0008,0120) shall be present.

I.e. you cannot use Long Code Value here because the value is < 16 characters. While this isn't relevant for the current PR under discussion, I think it is important that any test files we distribute are as correct as possible, as they will likely be used for tests for all sorts of other behaviour and also serve as exemplars on how to construct these files.

Can you think of other correct usage of Long Code Value that we could use here instead? Or alternatively we could revert the change to the file and create a tweaked version in memory during the test by setting it with some long string nonsense value.

**Review by CPBridge — CHANGES_REQUESTED** [review]
See above comment with requested changes

**Comment by rhaxton** [comment]
I reverted the test case file and added two test cases that modify in memory.  I reread the test file in each case to avoid modifying / testing / reverting the shared data, hopefully that is OK?

**Review by CPBridge — APPROVED** [review]
Looks good, thanks for your help @rhaxton

**Pull request merged**
