### PR TITLE
Remove JP2 wrapper from JPEG 2000 encoding

### PR DESCRIPTION
**Pull request by CPBridge**
Fix for #275

@erikogabrielsson

### CODE REVIEW

**Comment by CPBridge** [comment]
Tagging @hackermd for some help here.

**Comment by hackermd** [comment]
I think @erikogabrielsson is right and the content should be encoded as J2K (raw codestream) rather JP2 (file format). The `no_jp2` flag appears to achieve that goal.

**Comment by hackermd** [comment]
@CPBridge I think we need to update the unit test and check for the magic number of the JPEG2000 raw codestream (`b"\xFF\x4F\xFF\x51"`) instead:

https://github.com/ImagingDataCommons/highdicom/blob/v0.22.0/tests/test_frame.py#L174

**Comment by CPBridge** [comment]
Thanks both, I will put out a minor release relatively soon with this fix

**Pull request merged**
